import React from 'react';

function ModalDisclaimer(props) {

  return (
    <div className="Modal__card Modal__card--scrollable">
      <div className="Modal__scroll">
        <div className="Modal__content">
          <h2>Disclaimer</h2>
          <p>The LGIAsuper Retirement income calculator is provided by the Queensland Local Government Superannuation Board (ABN 94 085 088 484, AFS Licence Number 230511) and is current as at July 2021 but is subject to change.</p>
          <p>The results depicted are illustrative only and are based on limited inputs provided and the assumptions built into the calculator. To the extent permitted by law, neither the provider of the calculator, its service providers nor any of their related bodies accept any liability for any omissions, errors or inaracies in the results generated by the calculator or use thereof.</p>
          <p>The calculator is not intended to provide a recommendation in relation to a financial product or an interest in a financial product. The calculator is not intended to be relied upon as a substitute for professional advice. You should consider seeking professional advice from an Australian financial services licensee before making any decision. The results which you generate when using the calculator are dependent on the variables you input and the assumptions made by the calculator. As the variables and assumptions are unlikely to match your situation precisely, the results may not be appropriate for your financial situation. Please read 'About this calculator' which includes details of the assumptions used in this calculator, and their limitations.</p>
          <p>You should consider the product disclosure statement for a super fund and your personal circumstances in order to decide whether a super fund is suitable for you.</p>
          <p>This calculator has been designed and is supported by Willis Towers Watson.</p>
          <hr className="hr-double" />
          <label className="form__label form__label--checkbox form__label--clear flat" htmlFor="acceptDisc">
            <input type="checkbox" checked={props.acceptedDisc} id="acceptDisc" className="form__checkbox" onChange={props.onAcceptDisc} />
            I have read and understand this disclaimer and the assumptions and limitations outlined.
          </label>
        </div>
      </div>
      <footer className="Modal__footer">
        <button className="link Modal__cancel" onClick={props.onDismiss}>Cancel</button>
        <button disabled={!props.acceptedDisc} className="btn btn--secondary" onClick={props.onContinueDisc}>Continue</button>
      </footer>
    </div>
  )
}

export default ModalDisclaimer
